
import React, { useEffect, useRef, useState } from 'react';
import { Scene, AspectRatio, MediaType, Language, VisualEffect, StoryMetadata, SubtitleStyle } from '../types';
import { generateImage, animateImageWithVeo, generateVideoFromText, generateNarration, VISUAL_STYLES, VOICE_OPTIONS } from '../services/geminiService';
import { translations } from '../utils/translations';
import { decodeBase64, robustDecodeAudio } from '../utils/audioUtils';

interface VisualGeneratorProps {
  scenes: Scene[];
  aspectRatio: AspectRatio;
  language: Language;
  onUpdateScene: (id: string, updates: Partial<Scene>) => void;
  onDeleteScene: (id: string) => void;
  onComplete: (autoRender?: boolean) => void;
  visualStyle?: string; 
  metadata?: StoryMetadata; 
  autoDownloadEnabled: boolean; 
  autoAdvanceEnabled: boolean;
  selectedVoice: string;
  onVoiceChange: (voice: string) => void;
  subStyle: SubtitleStyle;
  onSubStyleChange: (style: SubtitleStyle) => void;
  bgMusicFile: File | null;
  onMusicChange: (file: File | null) => void;
  bgMusicVolume: number;
  onMusicVolChange: (vol: number) => void;
  narrationVolume: number;
  onNarrationVolChange: (vol: number) => void;
}

export const VisualGenerator: React.FC<VisualGeneratorProps> = ({ 
    scenes, aspectRatio, language, onUpdateScene, onDeleteScene, onComplete, visualStyle, metadata, autoDownloadEnabled, autoAdvanceEnabled, selectedVoice, onVoiceChange, subStyle, onSubStyleChange, bgMusicFile, onMusicChange, bgMusicVolume, onMusicVolChange, narrationVolume, onNarrationVolChange
}) => {
  const t = translations[language].visuals;
  const tp = translations[language].preview;
  const hasAutoGeneratedRef = useRef(false);
  const shouldStopRef = useRef(false);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'voice' | 'subs'>('voice');

  const getStyleModifier = () => {
      if (visualStyle) return `Visual Style: ${visualStyle}`;
      if (metadata?.consistentStyle) return `Visual Style: ${metadata.consistentStyle}`;
      return '';
  };

  const handleGenerateImage = async (scene: Scene) => {
    onUpdateScene(scene.id, { isGenerating: true, error: undefined });
    try {
      const modifier = getStyleModifier();
      const finalPrompt = modifier ? `${scene.visualPrompt}. ${modifier}` : scene.visualPrompt;
      const result = await generateImage(finalPrompt, aspectRatio);
      onUpdateScene(scene.id, { mediaType: MediaType.Image, mediaUrl: result.url, mediaMimeType: result.mimeType, isGenerating: false });
    } catch (e: any) {
      onUpdateScene(scene.id, { isGenerating: false, error: e.message });
    }
  };

  const handleAnimateVeo = async (scene: Scene) => {
    onUpdateScene(scene.id, { isGenerating: true, error: undefined });
    try {
      const modifier = getStyleModifier();
      const finalPrompt = modifier ? `${scene.visualPrompt}. ${modifier}` : scene.visualPrompt;
      let videoUrl: string;
      if (scene.mediaUrl && scene.mediaType === MediaType.Image) {
         videoUrl = await animateImageWithVeo(finalPrompt, scene.mediaUrl.split(',')[1], scene.mediaMimeType || 'image/png', aspectRatio);
      } else {
         videoUrl = await generateVideoFromText(finalPrompt, aspectRatio);
      }
      onUpdateScene(scene.id, { mediaType: MediaType.Video, mediaUrl: videoUrl, isGenerating: false });
    } catch (e: any) {
      onUpdateScene(scene.id, { isGenerating: false, error: e.message });
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>, sceneId: string) => {
    const file = e.target.files?.[0];
    if (file) onUpdateScene(sceneId, { mediaType: MediaType.Image, mediaUrl: URL.createObjectURL(file), mediaMimeType: file.type, isGenerating: false });
  };

  const runGenerationLoop = async () => {
      shouldStopRef.current = false;
      setIsAutoGenerating(true);
      for (const scene of scenes) {
            if (shouldStopRef.current) break;
            if (!scene.mediaUrl && !scene.isGenerating) {
                await handleGenerateImage(scene);
                await new Promise(r => setTimeout(r, 1500));
            }
      }
      setIsAutoGenerating(false);
  };

  useEffect(() => {
    if (!hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        runGenerationLoop();
    }
  }, []);

  return (
    <div className="max-w-7xl mx-auto animate-fade-in pb-20">
      <div className="flex justify-between items-center mb-10">
         <div>
            <h2 className="text-3xl font-black text-white tracking-tighter uppercase">{t.title}</h2>
            <p className="text-slate-500 text-xs font-bold tracking-widest mt-1">SISTEMA DE PRODUCCIÓN IA</p>
         </div>
         <div className="flex space-x-4">
             {isAutoGenerating ? (
                 <button onClick={() => shouldStopRef.current = true} className="bg-red-500/10 text-red-400 px-6 py-2 rounded-xl border border-red-500/20 text-[10px] font-black uppercase tracking-widest">{t.btnStop}</button>
             ) : (
                 <button onClick={runGenerationLoop} className="bg-indigo-600/10 text-indigo-400 px-6 py-2 rounded-xl border border-indigo-500/20 text-[10px] font-black uppercase tracking-widest">{t.btnResume}</button>
             )}
             <button onClick={() => onComplete(false)} className="bg-emerald-600 px-8 py-3 rounded-xl text-white text-[10px] font-black shadow-xl shadow-emerald-500/20 tracking-widest uppercase active:scale-95 transition-all">{t.btnProceed}</button>
         </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-8">
        <div className="flex-1 space-y-6">
            {scenes.map((scene, index) => (
                <div key={scene.id} className="glass-panel rounded-2xl p-6 flex flex-col md:flex-row gap-6 relative group border border-white/5 hover:border-white/10 transition-all">
                    <button onClick={() => onDeleteScene(scene.id)} className="absolute top-4 right-4 text-slate-600 hover:text-red-400 transition-colors"><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" strokeWidth={2}/></svg></button>
                    <div className="flex-1 space-y-4">
                        <div className="flex items-center space-x-2">
                            <span className="bg-indigo-500/10 text-indigo-400 text-[9px] font-black px-3 py-1 rounded-full uppercase tracking-widest">{t.scene} {index + 1}</span>
                            {scene.isCta && <span className="bg-amber-500/10 text-amber-400 text-[9px] font-black px-3 py-1 rounded-full uppercase tracking-widest">CTA</span>}
                        </div>
                        <textarea className="w-full bg-slate-950/50 border border-white/10 rounded-xl p-4 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-all leading-relaxed" value={scene.script} onChange={e => onUpdateScene(scene.id, { script: e.target.value })} />
                        
                        <div className="flex flex-wrap gap-3">
                            <button onClick={() => handleGenerateImage(scene)} disabled={scene.isGenerating} className="bg-indigo-600 hover:bg-indigo-500 px-5 py-2.5 rounded-xl text-[10px] font-black text-white transition-all active:scale-95 shadow-lg shadow-indigo-500/20 uppercase tracking-widest">{t.btnImgStd}</button>
                            <label className="bg-slate-800 hover:bg-slate-700 px-5 py-2.5 rounded-xl text-[10px] font-black text-white cursor-pointer uppercase tracking-widest">{t.btnUpload}<input type="file" accept="image/*" className="hidden" onChange={e => handleFileUpload(e, scene.id)} /></label>
                            <button onClick={() => handleAnimateVeo(scene)} disabled={scene.isGenerating} className="bg-slate-900 border border-purple-500/30 text-purple-400 px-5 py-2.5 rounded-xl text-[10px] font-black hover:bg-purple-900/20 transition-all uppercase tracking-widest">VEO PRO</button>
                        </div>

                        {scene.mediaUrl && scene.mediaType === MediaType.Image && (
                            <div className="flex items-center space-x-3 bg-slate-950/80 px-4 py-2 rounded-xl border border-white/5">
                                <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest">{t.effectLabel}</label>
                                <select className="bg-transparent text-[11px] font-bold text-white outline-none cursor-pointer flex-1" value={scene.visualEffect} onChange={e => onUpdateScene(scene.id, { visualEffect: e.target.value as VisualEffect })}>
                                    <option value={VisualEffect.Static}>{t.effects.static}</option>
                                    <option value={VisualEffect.ZoomIn}>{t.effects.zoomIn}</option>
                                    <option value={VisualEffect.ZoomOut}>{t.effects.zoomOut}</option>
                                    <option value={VisualEffect.PanLeft}>{t.effects.panLeft}</option>
                                    <option value={VisualEffect.PanRight}>{t.effects.panRight}</option>
                                    <option value={VisualEffect.TiltUp}>{t.effects.tiltUp}</option>
                                    <option value={VisualEffect.TiltDown}>{t.effects.tiltDown}</option>
                                    <option value={VisualEffect.DollyIn}>{t.effects.dollyIn}</option>
                                    <option value={VisualEffect.DollyOut}>{t.effects.dollyOut}</option>
                                </select>
                            </div>
                        )}
                    </div>
                    <div className="w-full md:w-64 aspect-video md:aspect-[9/16] bg-black rounded-xl overflow-hidden border border-white/10 flex items-center justify-center shadow-2xl">
                        {scene.isGenerating ? (
                            <div className="flex flex-col items-center space-y-3">
                                <div className="animate-spin h-6 w-6 border-b-2 border-indigo-500 rounded-full" />
                                <span className="text-[9px] font-black text-indigo-400 uppercase tracking-widest">Magic...</span>
                            </div>
                        ) : scene.mediaUrl ? (
                            scene.mediaType === MediaType.Video ? <video src={scene.mediaUrl} className="w-full h-full object-cover" autoPlay loop muted /> : <img src={scene.mediaUrl} className="w-full h-full object-cover" />
                        ) : (
                            <span className="text-[9px] text-slate-700 font-black uppercase tracking-widest">{t.statusEmpty}</span>
                        )}
                    </div>
                </div>
            ))}
        </div>
        
        <div className="lg:w-[320px] space-y-6">
            <div className="glass-panel rounded-2xl overflow-hidden flex flex-col sticky top-24">
               <div className="flex border-b border-white/5 bg-slate-950/50">
                   {['voice', 'subs'].map(tab => (
                       <button key={tab} onClick={() => setActiveTab(tab as any)} className={`flex-1 py-4 text-[10px] font-black uppercase tracking-widest ${activeTab === tab ? 'text-indigo-400 border-b-2 border-indigo-500 bg-indigo-500/5' : 'text-slate-500'}`}>{tab}</button>
                   ))}
               </div>
               <div className="p-6 space-y-5">
                    {activeTab === 'voice' && (
                        <div className="space-y-6">
                            <div className="space-y-4">
                                <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest">{tp.voiceLabel}</label>
                                <div className="space-y-3">
                                    {VOICE_OPTIONS.map(v => (
                                        <button
                                            key={v.name}
                                            onClick={() => onVoiceChange(v.name)}
                                            className={`w-full text-left p-3 rounded-xl border transition-all ${selectedVoice === v.name ? 'bg-indigo-600/20 border-indigo-500 text-white' : 'bg-slate-800 border-white/5 text-slate-400 hover:border-white/10'}`}
                                        >
                                            <div className="text-[11px] font-black uppercase tracking-tight">{(v as any).label || v.name}</div>
                                            <div className="text-[9px] mt-1 leading-tight opacity-60">{(v as any).style}</div>
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="pt-4 border-t border-white/5 space-y-3">
                                <div className="flex justify-between items-center">
                                    <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest">{tp.volLabel || "Volumen"}</label>
                                    <span className="text-[10px] font-mono text-indigo-400">{Math.round(narrationVolume * 100)}%</span>
                                </div>
                                <input 
                                    type="range" 
                                    min="0" 
                                    max="1" 
                                    step="0.01" 
                                    value={narrationVolume} 
                                    onChange={(e) => onNarrationVolChange(parseFloat(e.target.value))} 
                                    className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-indigo-500" 
                                />
                            </div>
                        </div>
                    )}
               </div>
            </div>
        </div>
      </div>
    </div>
  );
};
